version: "3.1"

services:
  armur-tools:
    build:
      context: .
      dockerfile: Dockerfile.tools
    image: armur-tools

  app:
    build: .
    container_name: api_service
    volumes:
      - shared_tmp:/armur/repos
    ports:
      - "4500:4500"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - APP_PORT=4500
      - REDIS_ADDR=redis_service:6379
    depends_on:
      - redis_service
    image: armur-code-scanner-app
  redis_service:
    image: "redis:alpine"
    container_name: redis_service
    ports:
      - "${REDIS_PORT:-6379}:6379"
volumes:
  shared_tmp: