version: "3.1"

services:
  app:
    build: .
    container_name: api_service
    volumes:
      - shared_tmp:/armur/repos
    ports:
      - "4500:4500"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - APP_PORT=4500
      - REDIS_ADDR=redis_service:6379
    depends_on:
      - redis_service
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  redis_service:
    image: "redis:alpine"
    container_name: redis_service
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
volumes:
  shared_tmp: